name: NEWIFI3-5-11-2019v2

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
    - name: Clone source
      run: |
        cd /home/runner
        git clone https://github.com/coolsnowwolf/lede.git
        sudo chmod -R 777 lede
        sudo chown -R runner:runner lede
        cd /home/runner/lede
        ./scripts/feeds update -a 
        ./scripts/feeds install -a
    - name: Change theme
      run: |
        cd /home/runner/lede/package/lean
        rm -rf luci-theme-argon
        git clone https://github.com/jerrykuku/luci-theme-argon.git
        sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' '/home/runner/lede/feeds/luci/collections/luci/Makefile'
    - name: Change config
      run: |
       sed -i "s/DISTRIB_REVISION='R9.10.24'/DISTRIB_REVISION='R9.11.5'/g" '/home/runner/lede/package/lean/default-settings/files/zzz-default-settings'
       sed -i "s/OpenWrt/By PiN1Group-wky/g" '/home/runner/lede/package/lean/default-settings/files/zzz-default-settings'
    - name : Change dhcp,theme and device name
      run: |
       sed -i 's/exit 0/#/g' '/home/runner/lede/package/lean/default-settings/files/zzz-default-settings'
       echo -e "uci set network.lan.proto='dhcp'\nuci set system.@system[0].hostname='NewPi'\nuci batch <<-EOF\n    set luci.themes.Argon=/luci-static/argon\n    set luci.main.mediaurlbase=/luci-static/argon\n    commit luci\nEOF\n\nexit 0" >> /home/runner/lede/package/lean/default-settings/files/zzz-default-settings
    - name: Clone config
      run: |
        cd /home/runner/lede/
        wget https://raw.githubusercontent.com/build-lede-NEWIFI3/build-test/master/.config
    - name: Build
      run: | 
        cd /home/runner/lede 
        make -j2
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/lede/bin
